"""support tables

Revision ID: 739998732fab
Revises: 3e4f60433d23
Create Date: 2026-07-24 17:07:43.219583

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '739998732fab'
down_revision: str | None = '3e4f60433d23'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_conversation',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('tg_chat_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_username', sa.String(), nullable=True),
    sa.Column('lang', sa.String(), nullable=True),
    sa.Column('status', sa.String(), server_default=sa.text("'open'"), nullable=False),
    sa.Column('unread_count', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('last_message_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('open', 'pending', 'closed')", name=op.f('ck_support_conversation_support_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_conversation')),
    sa.UniqueConstraint('tg_chat_id', name=op.f('uq_support_conversation_tg_chat_id'))
    )
    op.create_index('ix_support_conversation_status_last', 'support_conversation', ['status', 'last_message_at'], unique=False)
    op.create_table('support_message',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_staff_id', sa.BigInteger(), nullable=True),
    sa.Column('delivery', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("delivery IS NULL OR delivery IN ('sent', 'failed')", name=op.f('ck_support_message_support_delivery_valid')),
    sa.CheckConstraint("direction IN ('in', 'out')", name=op.f('ck_support_message_support_direction_valid')),
    sa.ForeignKeyConstraint(['conversation_id'], ['support_conversation.id'], name=op.f('fk_support_message_conversation_id_support_conversation'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_staff_id'], ['app_user.id'], name=op.f('fk_support_message_sender_staff_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_support_message'))
    )
    op.create_index('ix_support_message_conversation_created', 'support_message', ['conversation_id', 'created_at'], unique=False)


def downgrade() -> None:
    op.drop_index('ix_support_message_conversation_created', table_name='support_message')
    op.drop_table('support_message')
    op.drop_index('ix_support_conversation_status_last', table_name='support_conversation')
    op.drop_table('support_conversation')
