"""reviews and ratings

Revision ID: 838b3223574e
Revises: 86d06fe6750a
Create Date: 2026-07-26 00:00:00.000000

Adds the ``review`` table (Reviews & Ratings §2): one review per
``(product_id, user_id)`` with CASCADE FKs to product and app_user, a rating
CHECK (1..5), a status CHECK (pending|approved|rejected), a lang CHECK (ru|ro),
and two lookup indexes — ``(product_id, status)`` for the public approved list
and ``(status)`` for the moderation queue.

Hand-written (not autogenerated) so it carries only this table and none of the
spurious drop_index ops autogenerate emits for hand-created indexes elsewhere.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "838b3223574e"
down_revision: str | None = "86d06fe6750a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "review",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("rating", sa.SmallInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("author_name", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("moderated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating BETWEEN 1 AND 5",
            name=op.f("ck_review_rating_range"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'rejected')",
            name=op.f("ck_review_status_allowed"),
        ),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')",
            name=op.f("ck_review_lang_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_review_product_id_product"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["app_user.id"],
            name=op.f("fk_review_user_id_app_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review")),
        sa.UniqueConstraint(
            "product_id",
            "user_id",
            name=op.f("uq_review_product_id"),
        ),
    )
    op.create_index(
        "ix_review_product_status",
        "review",
        ["product_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_review_status",
        "review",
        ["status"],
        unique=False,
    )


def downgrade() -> None:
    op.drop_index("ix_review_status", table_name="review")
    op.drop_index("ix_review_product_status", table_name="review")
    op.drop_table("review")
