"""domain schema v1

Revision ID: 928ef6e9feec
Revises: 0001_baseline
Create Date: 2026-07-20 10:07:46.298916

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op
from app.models.base import CITEXT

# revision identifiers, used by Alembic.
revision: str = "928ef6e9feec"
down_revision: str | None = "0001_baseline"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # citext extension must exist before any CITEXT column is created (§2.2).
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", CITEXT(), nullable=False),
        sa.Column("password_hash", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_staff", sa.Boolean(), nullable=False),
        sa.Column("loyalty_points", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_app_user")),
        sa.UniqueConstraint("email", name=op.f("uq_app_user_email")),
        sa.UniqueConstraint("phone", name=op.f("uq_app_user_phone")),
    )
    op.create_table(
        "attribute",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute")),
        sa.UniqueConstraint("code", name=op.f("uq_attribute_code")),
    )
    op.create_table(
        "category",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("path", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("depth", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["category.id"], name=op.f("fk_category_parent_id_category")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_category")),
    )
    op.create_table(
        "promo_code",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("discount_type", sa.String(), nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("active_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("active_to", sa.DateTime(timezone=True), nullable=False),
        sa.Column("min_order_total", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("usage_limit", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "discount_type IN ('percent', 'fixed')",
            name=op.f("ck_promo_code_promo_code_discount_type_valid"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_promo_code")),
        sa.UniqueConstraint("code", name=op.f("uq_promo_code_code")),
    )
    op.create_table(
        "address",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("city", sa.String(), nullable=False),
        sa.Column("street", sa.String(), nullable=False),
        sa.Column("zip", sa.String(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_address_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_address")),
    )
    op.create_table(
        "attribute_translation",
        sa.Column("attribute_id", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')", name=op.f("ck_attribute_translation_lang_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute.id"],
            name=op.f("fk_attribute_translation_attribute_id_attribute"),
        ),
        sa.PrimaryKeyConstraint(
            "attribute_id", "lang", name=op.f("pk_attribute_translation")
        ),
    )
    op.create_table(
        "attribute_value",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("attribute_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute.id"],
            name=op.f("fk_attribute_value_attribute_id_attribute"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attribute_value")),
    )
    op.create_table(
        "cart",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("session_token", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "status IN ('draft', 'converted', 'abandoned')",
            name=op.f("ck_cart_cart_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_cart_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart")),
    )
    op.create_table(
        "category_translation",
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("seo_title", sa.Text(), nullable=True),
        sa.Column("seo_description", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')", name=op.f("ck_category_translation_lang_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_category_translation_category_id_category"),
        ),
        sa.PrimaryKeyConstraint(
            "category_id", "lang", name=op.f("pk_category_translation")
        ),
        sa.UniqueConstraint("lang", "slug", name=op.f("uq_category_translation_lang")),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("code", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
            name=op.f("fk_product_category_id_category"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product")),
        sa.UniqueConstraint("code", name=op.f("uq_product_code")),
    )
    op.create_table(
        "attribute_value_translation",
        sa.Column("value_id", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')",
            name=op.f("ck_attribute_value_translation_lang_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["value_id"],
            ["attribute_value.id"],
            name=op.f("fk_attribute_value_translation_value_id_attribute_value"),
        ),
        sa.PrimaryKeyConstraint(
            "value_id", "lang", name=op.f("pk_attribute_value_translation")
        ),
    )
    op.create_table(
        "cart_item",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("cart_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cart_id"], ["cart.id"], name=op.f("fk_cart_item_cart_id_cart")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_cart_item_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cart_item")),
        sa.UniqueConstraint("cart_id", "product_id", name="cart_item_cart_product"),
    )
    op.create_table(
        "media",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind IN ('image')", name=op.f("ck_media_kind_allowed")),
        sa.ForeignKeyConstraint(
            ["product_id"], ["product.id"], name=op.f("fk_media_product_id_product")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_media")),
    )
    op.create_table(
        "order",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("number", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("email", CITEXT(), nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("payment_status", sa.String(), nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("discount_total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_cost", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("total", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("delivery_type", sa.String(), nullable=False),
        sa.Column("delivery_address_id", sa.BigInteger(), nullable=True),
        sa.Column("payment_method", sa.String(), nullable=False),
        sa.Column("promo_code", sa.String(), nullable=True),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.CheckConstraint(
            "delivery_type IN ('pickup', 'courier')",
            name=op.f("ck_order_order_delivery_type_valid"),
        ),
        sa.CheckConstraint(
            "payment_status IN ('pending', 'paid', 'refunded')",
            name=op.f("ck_order_order_payment_status_valid"),
        ),
        sa.CheckConstraint(
            "status IN ('new', 'confirmed', 'done', 'canceled')",
            name=op.f("ck_order_order_status_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["delivery_address_id"],
            ["address.id"],
            name=op.f("fk_order_delivery_address_id_address"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["app_user.id"], name=op.f("fk_order_user_id_app_user")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order")),
        sa.UniqueConstraint("number", name=op.f("uq_order_number")),
    )
    op.create_table(
        "product_attribute",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("value_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_attribute_product_id_product"),
        ),
        sa.ForeignKeyConstraint(
            ["value_id"],
            ["attribute_value.id"],
            name=op.f("fk_product_attribute_value_id_attribute_value"),
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "value_id", name=op.f("pk_product_attribute")
        ),
    )
    op.create_table(
        "product_card",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("category_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("price", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("old_price", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("in_stock", sa.Boolean(), nullable=False),
        sa.Column("main_image_url", sa.Text(), nullable=True),
        sa.Column("badge", sa.String(), nullable=True),
        sa.Column("path", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')", name=op.f("ck_product_card_lang_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_card_product_id_product"),
        ),
        sa.PrimaryKeyConstraint("product_id", "lang", name=op.f("pk_product_card")),
    )
    op.create_table(
        "product_translation",
        sa.Column("product_id", sa.BigInteger(), nullable=False),
        sa.Column("lang", sa.String(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("seo_title", sa.Text(), nullable=True),
        sa.Column("seo_description", sa.Text(), nullable=True),
        sa.Column("search_vector", postgresql.TSVECTOR(), nullable=True),
        sa.CheckConstraint(
            "lang IN ('ru', 'ro')", name=op.f("ck_product_translation_lang_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_product_translation_product_id_product"),
        ),
        sa.PrimaryKeyConstraint(
            "product_id", "lang", name=op.f("pk_product_translation")
        ),
        sa.UniqueConstraint("lang", "slug", name=op.f("uq_product_translation_lang")),
    )
    op.create_table(
        "order_item",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("name_snapshot", sa.String(), nullable=False),
        sa.Column("price_snapshot", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("qty", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"], ["order.id"], name=op.f("fk_order_item_order_id_order")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
            name=op.f("fk_order_item_product_id_product"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_item")),
    )
    op.create_table(
        "order_status_history",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("order_id", sa.BigInteger(), nullable=False),
        sa.Column("from_status", sa.String(), nullable=False),
        sa.Column("to_status", sa.String(), nullable=False),
        sa.Column("changed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("changed_by", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["order.id"],
            name=op.f("fk_order_status_history_order_id_order"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_status_history")),
    )
    # ### end Alembic commands ###

    # --- Performance indexes (§5.1). Autogenerate does not emit partial/GIN. ---
    # Hot listing path.
    op.create_index(
        "ix_product_category_active", "product", ["category_id", "is_active"]
    )
    # Listing sorts (partial: only active rows).
    op.create_index(
        "ix_product_price",
        "product",
        ["price"],
        postgresql_where=sa.text("is_active"),
    )
    op.create_index(
        "ix_product_created",
        "product",
        [sa.text("created_at DESC")],
        postgresql_where=sa.text("is_active"),
    )
    # Facets: attribute-value aggregation (product_id already covered by PK prefix).
    op.create_index("ix_product_attribute_value", "product_attribute", ["value_id"])
    # Category tree.
    op.create_index("ix_category_parent", "category", ["parent_id"])
    op.create_index("ix_category_path", "category", ["path"], postgresql_using="gin")
    # FTS: search_vector lives on product_translation (corrected §5.1 / §6.1).
    op.create_index(
        "ix_product_tr_search",
        "product_translation",
        ["search_vector"],
        postgresql_using="gin",
    )

    # --- FTS trigger (§6.1): fill search_vector per-language (russian/romanian). ---
    # The tsearch config depends on NEW.lang, which is not IMMUTABLE, so a GENERATED
    # column cannot be used — a BEFORE trigger populates the vector instead.
    op.execute(
        """
        CREATE FUNCTION trg_product_tr_search() RETURNS trigger AS $$
        DECLARE cfg regconfig := CASE NEW.lang
            WHEN 'ru' THEN 'russian'::regconfig
            WHEN 'ro' THEN 'romanian'::regconfig
            ELSE 'simple'::regconfig END;
        BEGIN
            NEW.search_vector :=
                setweight(to_tsvector(cfg, coalesce(NEW.name, '')), 'A')
             || setweight(to_tsvector(cfg, coalesce(NEW.description, '')), 'B');
            RETURN NEW;
        END $$ LANGUAGE plpgsql;
        """
    )
    op.execute(
        """
        CREATE TRIGGER product_translation_search_vector
        BEFORE INSERT OR UPDATE OF name, description, lang ON product_translation
        FOR EACH ROW EXECUTE FUNCTION trg_product_tr_search();
        """
    )


def downgrade() -> None:
    # FTS function is a standalone object (the trigger drops with its table).
    op.execute("DROP FUNCTION IF EXISTS trg_product_tr_search() CASCADE")
    # Table-bound indexes are dropped together with their tables below.
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("order_status_history")
    op.drop_table("order_item")
    op.drop_table("product_translation")
    op.drop_table("product_card")
    op.drop_table("product_attribute")
    op.drop_table("order")
    op.drop_table("media")
    op.drop_table("cart_item")
    op.drop_table("attribute_value_translation")
    op.drop_table("product")
    op.drop_table("category_translation")
    op.drop_table("cart")
    op.drop_table("attribute_value")
    op.drop_table("attribute_translation")
    op.drop_table("address")
    op.drop_table("promo_code")
    op.drop_table("category")
    op.drop_table("attribute")
    op.drop_table("app_user")
    # ### end Alembic commands ###
