"""site_setting table + app_user.role placeholder (admin §6.4)

Revision ID: a1b2c3d4e5f6
Revises: 3265425b6a22
Create Date: 2026-07-20 23:40:00.000000

Hand-written (not autogenerated): autogenerate proposes dropping several
functional/partial indexes it cannot introspect (category path/parent, product
partial indexes, FTS gin) — false positives. This migration only adds the new
``site_setting`` table and a nullable ``app_user.role`` column.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a1b2c3d4e5f6"
down_revision: str | None = "3265425b6a22"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "site_setting",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_site_setting")),
    )
    op.add_column("app_user", sa.Column("role", sa.String(), nullable=True))


def downgrade() -> None:
    op.drop_column("app_user", "role")
    op.drop_table("site_setting")
