"""product + variant shipping weight in grams (Nova Post phase P0)

Revision ID: b1c2d3e4f5a6
Revises: a7c3e9f1b2d5
Create Date: 2026-07-31 09:20:00.000000

Hand-written (not autogenerated). Adds a nullable ``weight_g`` to ``product`` and
``product_variant``: the shipping weight a carrier prices a parcel by. NULL means
"not entered yet" — the delivery service substitutes a configured default rather
than guessing zero, and the back-office can list what is still missing.

Nullable on purpose: the imported catalogue carries no weight at all (the
flystore scrape has no such field), so a NOT NULL column would force a fake value
onto 658 products and make "unknown" indistinguishable from "really light".

The variant column overrides the product one for variable products, mirroring how
``price``/``qty`` already work there.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b1c2d3e4f5a6"
down_revision: str | None = "a7c3e9f1b2d5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column("product", sa.Column("weight_g", sa.Integer(), nullable=True))
    op.add_column("product_variant", sa.Column("weight_g", sa.Integer(), nullable=True))
    # Partial index for the back-office "weight not set" queue: it only ever
    # scans the missing rows, and shrinks to nothing as the catalogue is filled.
    op.create_index(
        "ix_product_weight_missing",
        "product",
        ["id"],
        postgresql_where=sa.text("weight_g IS NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_product_weight_missing", table_name="product")
    op.drop_column("product_variant", "weight_g")
    op.drop_column("product", "weight_g")
