"""visit analytics table (admin §6.3)

Revision ID: b2c3d4e5f6a7
Revises: a1b2c3d4e5f6
Create Date: 2026-07-20 23:55:00.000000

Hand-written (not autogenerated) to avoid the known false-positive index drops.
Adds the first-party ``visit`` pageview log plus a range index on
``occurred_at`` for the dashboard's time-bucketed queries.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b2c3d4e5f6a7"
down_revision: str | None = "a1b2c3d4e5f6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "visit",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column(
            "occurred_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("path", sa.String(), nullable=False),
        sa.Column("referrer", sa.String(), nullable=True),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("device", sa.String(), nullable=False),
        sa.Column("is_bot", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_visit")),
    )
    op.create_index("ix_visit_occurred_at", "visit", ["occurred_at"], unique=False)


def downgrade() -> None:
    op.drop_index("ix_visit_occurred_at", table_name="visit")
    op.drop_table("visit")
