"""order delivery service + Nova Post shipment data (phase P2)

Revision ID: c2d3e4f5a6b7
Revises: b1c2d3e4f5a6
Create Date: 2026-07-31 12:55:00.000000

Hand-written (not autogenerated). Splits "how it is delivered" from "who
delivers it":

* ``order.delivery_service`` — ``own`` (pickup / our flat-rate courier) or
  ``novapost``. Existing rows default to ``own``, which is what they are.
* ``order.delivery_type`` gains ``branch`` and ``postomat`` alongside the
  existing ``pickup`` / ``courier``. The pair is what identifies a method:
  ``own+courier`` is our courier, ``novapost+courier`` is the carrier's.
* ``order_delivery_np`` — one row per carrier order, holding the snapshot of
  where it goes (city / pickup point / address), what the carrier quoted, and
  the waybill with its tracking status.

The snapshot columns repeat data the carrier could return, on purpose: an order
must stay readable years later without calling a third party that may have
renamed a branch or gone away. Same reasoning as the existing
``order.delivery_*`` address snapshot.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c2d3e4f5a6b7"
down_revision: str | None = "b1c2d3e4f5a6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

_OLD_TYPES = "'pickup', 'courier'"
_NEW_TYPES = "'pickup', 'courier', 'branch', 'postomat'"


def upgrade() -> None:
    op.add_column(
        "order",
        sa.Column(
            "delivery_service",
            sa.String(),
            nullable=False,
            server_default="own",
        ),
    )
    op.create_check_constraint(
        "order_delivery_service_valid",
        "order",
        "delivery_service IN ('own', 'novapost')",
    )
    op.drop_constraint("order_delivery_type_valid", "order", type_="check")
    op.create_check_constraint(
        "order_delivery_type_valid",
        "order",
        f"delivery_type IN ({_NEW_TYPES})",
    )

    op.create_table(
        "order_delivery_np",
        sa.Column(
            "order_id",
            sa.BigInteger(),
            sa.ForeignKey("order.id", ondelete="CASCADE"),
            primary_key=True,
        ),
        # Where it goes: carrier ids plus the human-readable snapshot.
        sa.Column("settlement_id", sa.String(), nullable=True),
        sa.Column("settlement_name", sa.String(), nullable=False, server_default=""),
        sa.Column("settlement_name_ru", sa.String(), nullable=False, server_default=""),
        sa.Column("division_id", sa.String(), nullable=True),
        sa.Column("division_number", sa.String(), nullable=False, server_default=""),
        sa.Column("division_address", sa.String(), nullable=False, server_default=""),
        # Courier-to-the-door address as the carrier expects it.
        sa.Column(
            "address_parts",
            sa.dialects.postgresql.JSONB(),
            nullable=True,
        ),
        # What the carrier quoted at checkout (kept next to order.delivery_cost,
        # which may differ once a free-delivery threshold applies).
        sa.Column("calculated_cost", sa.Numeric(12, 2), nullable=True),
        # Waybill + tracking.
        sa.Column("awb_id", sa.String(), nullable=True),
        sa.Column("awb_number", sa.String(), nullable=True),
        sa.Column("awb_data", sa.dialects.postgresql.JSONB(), nullable=True),
        sa.Column("status_code", sa.String(), nullable=False, server_default=""),
        sa.Column("status_text", sa.String(), nullable=False, server_default=""),
        sa.Column("status_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
    )
    # The tracking sweep selects open waybills; a partial index keeps that scan
    # proportional to what is still in flight rather than to order history.
    op.create_index(
        "ix_order_delivery_np_open_awb",
        "order_delivery_np",
        ["order_id"],
        postgresql_where=sa.text("awb_number IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_index("ix_order_delivery_np_open_awb", table_name="order_delivery_np")
    op.drop_table("order_delivery_np")
    op.drop_constraint("order_delivery_type_valid", "order", type_="check")
    op.create_check_constraint(
        "order_delivery_type_valid",
        "order",
        f"delivery_type IN ({_OLD_TYPES})",
    )
    op.drop_constraint("order_delivery_service_valid", "order", type_="check")
    op.drop_column("order", "delivery_service")
