"""snapshot the quoted parcel weight on the carrier row (phase P4)

Revision ID: d3e4f5a6b7c8
Revises: c2d3e4f5a6b7
Create Date: 2026-07-31 15:10:00.000000

Hand-written (not autogenerated). The waybill is created from the back-office,
possibly days after the order — but it must declare the weight the customer was
*quoted* for, not whatever the catalogue says today. Products get edited, and
``order_item.product_id`` is ``ON DELETE SET NULL``, so recomputing later can
silently produce a different parcel (and a different bill).

Nullable: rows created before this migration have no snapshot, and the shipment
builder falls back to recomputing from the order lines for them.
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d3e4f5a6b7c8"
down_revision: str | None = "c2d3e4f5a6b7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.add_column(
        "order_delivery_np",
        sa.Column("parcel_weight_g", sa.Integer(), nullable=True),
    )


def downgrade() -> None:
    op.drop_column("order_delivery_np", "parcel_weight_g")
