"""order.delivery_address_id FK ON DELETE SET NULL (BUG-006 / TASK-4)

Revision ID: e5f6a7b8c9d0
Revises: a1d7decc1677
Create Date: 2026-07-25 00:00:00.000000

Hand-written (not autogenerated). The ``order.delivery_address_id`` FK was
declared without an ``ON DELETE`` action, so Postgres defaulted to RESTRICT:
deleting an address referenced by a courier order raised ``IntegrityError``
(surfacing as HTTP 500 on ``DELETE /users/me/addresses/{id}`` and breaking
account erasure). The order already snapshots the delivery address inline
(``delivery_name/city/street/zip``) and never re-reads ``delivery_address_id``
after creation, so the FK is functionally redundant. Switching it to
``SET NULL`` lets the DB null the link on address deletion while the snapshot
survives — consistent with ``order_item.product_id`` (already SET NULL).
"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e5f6a7b8c9d0"
down_revision: str | None = "a1d7decc1677"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.drop_constraint(
        "fk_order_delivery_address_id_address", "order", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_order_delivery_address_id_address",
        "order",
        "address",
        ["delivery_address_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        "fk_order_delivery_address_id_address", "order", type_="foreignkey"
    )
    op.create_foreign_key(
        "fk_order_delivery_address_id_address",
        "order",
        "address",
        ["delivery_address_id"],
        ["id"],
    )
