"""Declarative base and shared mixins.

B0 defines only the infrastructure: a :class:`Base` carrying a MetaData with an
explicit constraint naming convention (required for stable Alembic autogenerate)
and a :class:`TimestampMixin`. Domain models arrive in later stages (B1+).
"""

from datetime import datetime

from sqlalchemy import MetaData, func
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.types import UserDefinedType


class CITEXT(UserDefinedType):
    """PostgreSQL ``citext`` (case-insensitive text) column type.

    Requires ``CREATE EXTENSION IF NOT EXISTS citext`` (added by the baseline
    migration). Used for case-insensitive-unique fields like ``email``.
    """

    cache_ok = True

    def get_col_spec(self, **kw: object) -> str:
        return "CITEXT"


# Explicit naming convention so autogenerated constraints have deterministic names.
NAMING_CONVENTION: dict[str, str] = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base for all ORM models."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class TimestampMixin:
    """Adds ``created_at`` / ``updated_at`` columns with DB-side defaults."""

    created_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
